
### A Note on how these definitions were generated
#
# Definition 1     : generated by asking chatgpt o3 to generate a definition similar
#                    to the one we had for stereotypes.
#
# Definition 2     : generated by asking gpt-o3 model to base itself on popular books such as:
#                    - "Brief Treatise on Manipulation for Honest People" by Robert-Vincent Joule and 
#                       Jean-Léon Beauvois
#                    - "Influence: The Psychology of Persuasion" by Robert Cialdini
#                    - "In Sheep's Clothing: Understanding and Dealing With Manipulative People" by 
#                       George K. Simmons Junior
#                    - "30 Covert Emotional Manipulation Tactics: How Manipulators Take Control In 
#                       Personal Relationships" by Adelyn Birch
#                    and again to generate a definition similar to the one for stereotypes.
#                    Since it was relying too much on tactics names, I asked it to use generic titles
#                    for sections and subsections.


mental_manipulation_def1 = """ 
Mental manipulation occurs when an actor intentionally steers another person’s thoughts, emotions, or decisions by covertly exploiting psychological biases, informational asymmetries, or emotional vulnerabilities, thereby bypassing the target’s informed, rational autonomy and benefiting the manipulator at the target’s expense.

Key points include:
1. **Influence Mechanisms**
    1.a) **Cognitive Distortion**: Supplying misleading or selectively framed information to warp perception (e.g., “Everyone agrees with me—there’s no real debate”).  
    1.b) **Emotional Leverage**: Triggering guilt, fear, love, or shame to pressure compliance (e.g., “If you cared about us, you’d sign right now”).  
    1.c) **Gaslighting**: Undermining the target’s memory or sanity (e.g., “That never happened; you’re imagining things”).  
    1.d) **False Scarcity or Urgency**: Manufacturing deadlines or limited availability (e.g., “This offer vanishes in ten minutes”).  
    1.e) **Isolation & Echo Chambers**: Restricting diverse viewpoints to amplify the manipulator’s narrative.

2. **Contextual Risk Factors**
    A scenario is especially prone to manipulation when it features:  
    2.a) **Power Imbalance**: One party wields authority, status, or critical resources.  
    2.b) **Information Asymmetry**: The manipulator withholds or distorts key facts.  
    2.c) **Emotional Dependency**: The target relies on the manipulator for affection, approval, or belonging.  
    2.d) **Cognitive Overload**: Stress, fatigue, or complexity that impairs careful reasoning.

3. **Psychological Tactics**
    Manipulative actors commonly deploy:  
    3.a) **Appeal to Authority/Consensus**: “Experts/everyone says this—trust me.”  
    3.b) **False Dilemmas**: Presenting only two extreme options (“You’re with us or against us”).  
    3.c) **Pre-emptive Guilt or Shaming**: Framing dissent as selfish or disloyal.  
    3.d) **Flattery & Idealization**: Over-praising to lower skepticism (“Only someone as brilliant as you would understand”).  
    3.e) **Repetition & Priming**: Saturating channels with the same message to normalize it.

4. **Linguistic & Behavioral Indicators**
    4.a) **Presumptive Language**: Statements that take agreement for granted (“Obviously you’ll vote yes”).  
    4.b) **Loaded Questions**: Embedding assumptions that trap the target (“Why are you always so ungrateful?”).  
    4.c) **Vagueness & Ambiguity**: Avoiding specifics to escape scrutiny.  
    4.d) **Confusion Techniques**: Rapid topic shifts or jargon to overwhelm analysis.

5. **Harms and Consequences**
    Mental manipulation becomes harmful when it:  
    5.a) **Erodes Autonomy**: Decisions cease to reflect the target’s authentic will.  
    5.b) **Induces Psychological Distress**: Anxiety, self-doubt, or dependence.  
    5.c) **Distorts Reality Testing**: Persistent inability to trust memories or perceptions.  
    5.d) **Foments Exploitation**: Financial, relational, or political abuse.  
    5.e) **Undermines Social Trust**: Broad skepticism toward institutions or relationships.

6. **Intent and Ethical Line**
    6.a) **Transparent Persuasion**: Presents factual arguments, respects consent.  
    6.b) **Manipulation**: Conceals intent, exploits vulnerabilities, and prioritizes the manipulator’s gain over the target’s informed interests.

In summary, a message or act is deemed mental manipulation when it covertly commandeers psychological or emotional levers to override informed consent, particularly in contexts of power asymmetry, information control, or emotional dependency. The use of deceptive or pressuring tactics leads to distorted autonomy, psychological harm, and erosion of trust—distinguishing manipulation from legitimate, transparent persuasion.
"""

mental_manipulation_def1_short = """
"Covert use of language or behavior to emotionally pressure, deceive, or distort a person’s decisions for someone else’s benefit."

A response is manipulative if:
- It hides intent
- It creates emotional pressure
- It reduces the other person's freedom to choose

If none apply, label it: **Not Manipulative**"""


mental_manipulation_def2 = """ 
Mental manipulation happens when one party covertly shapes another person’s thoughts, feelings, or actions by exploiting built-in thinking shortcuts, emotional needs, or social pressures, thereby steering outcomes toward the influencer’s benefit while eroding the target’s fully informed, voluntary choice.

Key points include:

1. **Tactics**  
    1.a) **Incremental Request**: Securing a small “yes” first, then escalating the demand (classic foot-in-the-door / low-ball approach).  
    1.b) **Contrast Request**: Starting with an extreme proposal, then retreating to a milder one that now feels reasonable (door-in-the-face).  
    1.c) **Induced Obligation**: Giving unsolicited favors or gifts to create a felt need to reciprocate.  
    1.d) **Pressure of Shortage**: Using limited-time or limited-quantity cues to rush decisions.  
    1.e) **Appeal to Authority / Popularity**: Invoking expert opinion or social consensus to mute independent judgment.  
    1.f) **Reality Distortion**: Undermining perceptions or memory so the target doubts their own grasp of events (gaslighting).  
    1.g) **Excessive Affection**: Flooding with praise or attention to lower skepticism and build dependence (love-bombing).

2. **Human Tendencies Targeted**  
    2.a) **Thinking Biases**: Confirmation, anchoring, framing, optimism, etc.  
    2.b) **Emotional Drives**: Longing for belonging, approval, safety, or fear reduction.  
    2.c) **Need for Consistency**: Pressure to act in line with prior commitments and self-image.  
    2.d) **Mental Shortcuts**: Reliance on heuristics when time, energy, or information is limited.

3. **Situational Factors**  
    3.a) **Unequal Power**: One side controls resources, status, or decision authority.  
    3.b) **Hidden Information**: Key facts are withheld, distorted, or cherry-picked.  
    3.c) **High Load or Stress**: Fatigue, time crunch, or complexity that hampers careful thinking.  
    3.d) **Limited Perspectives**: Social isolation or echo chambers that block counter-arguments.

4. **Consequences**  
    4.a) **Reduced Autonomy**: Choices no longer reflect the target’s true preferences.  
    4.b) **Emotional Harm**: Heightened anxiety, guilt, self-doubt, or dependency.  
    4.c) **Unwanted Actions**: Financial, relational, or moral concessions the target later regrets.  
    4.d) **Broken Trust**: Long-term damage to relationships or institutional credibility.  
    4.e) **Deepening Control**: Successful tactics reinforce further compliance and make exit harder.

5. **Warning Signs**  
    5.a) **Presumptive Statements**: Language that assumes consent (“Obviously you’ll sign”).  
    5.b) **Moving Targets**: Demands that shift after each concession.  
    5.c) **Vague Language**: Lack of specifics that prevents close scrutiny.  
    5.d) **Emotional Swings**: Rapid alternation between praise and criticism to destabilize.  
    5.e) **Conditional Approval**: Affection or acceptance granted only if demands are met.

6. **Ethical Line**  
    6.a) **Open Influence**: Transparent facts, clear motives, respect for voluntary choice.  
    6.b) **Hidden Influence**: Concealed intent, reality distortion, or emotional weaponization.  
    6.c) **Consent Test**: An influence attempt qualifies as manipulation if it would likely fail were the target fully aware of the tactic, motives, and potential effects.

In summary, mental manipulation covertly taps into cognitive shortcuts, emotions, and situational pressures to override informed consent—especially when power and information are unbalanced—thereby undermining autonomy, inflicting psychological harm, and eroding trust. Transparent, respectful persuasion stops at the point where informed, voluntary choice remains intact; manipulation crosses that line.
"""